name: Cypress CI/CD

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  # Job 1 - Install deps
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm ci

  # Job 2 - Run BDD feature tests
  cypress-bdd-tests:
    runs-on: ubuntu-latest
    needs: install   # waits for install to finish
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npx cypress verify
      - name: Run BDD Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          spec: "cypress/e2e/features/**/*.feature"

  # Job 3 - Run normal Cypress tests
  cypress-ui-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "npm"
      - run: npm ci
      - run: npx cypress verify
      - name: Run UI Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          spec: "cypress/e2e/**/*.cy.js"
