name: Build and Test with Cypress
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Clean node_modules
        run: rm -rf node_modules

      - name: Install dependencies
        run: npm install

      - name: Install Cypress globally
        run: npm install -g cypress

      - name: Verify Cypress installation
        run: npx cypress verify

      - name: Run Cypress tests
        run: npx cypress run --spec "cypress/e2e/features/**/*.feature"
